#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUILD_DIR="${ROOT_DIR}/build/debug"

# Do not hardcode a compiler: lint must exercise the same toolchain the
# developer's build configured. If AGAMEMNON_LINT_C_COMPILER /
# AGAMEMNON_LINT_CXX_COMPILER are explicitly set, forward them; otherwise run
# plain `cmake --preset debug` and let CMake reuse whatever compiler is already
# recorded in build/debug/CMakeCache.txt (or its default). Configure failures
# abort under set -e rather than being silently swallowed: linting against a
# stale configure cache hides breakage.
CMAKE_COMPILER_ARGS=()
if [ -n "${AGAMEMNON_LINT_C_COMPILER:-}" ]; then
  CMAKE_COMPILER_ARGS+=("-DCMAKE_C_COMPILER=${AGAMEMNON_LINT_C_COMPILER}")
fi
if [ -n "${AGAMEMNON_LINT_CXX_COMPILER:-}" ]; then
  CMAKE_COMPILER_ARGS+=("-DCMAKE_CXX_COMPILER=${AGAMEMNON_LINT_CXX_COMPILER}")
fi
cmake --preset debug "${CMAKE_COMPILER_ARGS[@]}"

if [ ! -f "${BUILD_DIR}/compile_commands.json" ]; then
  echo "error: ${BUILD_DIR}/compile_commands.json not found; cannot run clang-tidy" >&2
  exit 1
fi

# Load the -isystem directories generated by cmake/ClangTidyIncludes.cmake
# (#211). The file is validated before use: unknown format versions and
# malformed lines are rejected loudly instead of silently regressing header
# resolution under conda/pixi GCC sysroots.
EXTRA_ARGS_FILE="${BUILD_DIR}/clang-tidy-extra-args.txt"
EXTRA_ARGS=()
if [ ! -f "${EXTRA_ARGS_FILE}" ]; then
  echo "warn: ${EXTRA_ARGS_FILE} missing; clang-tidy will rely on its built-in include resolution." >&2
  echo "warn: run 'cmake --preset debug' (with Agamemnon_ENABLE_CLANG_TIDY=ON, the default) to regenerate it." >&2
elif ! head -n1 "${EXTRA_ARGS_FILE}" | grep -q '^# format-version: 1$'; then
  echo "warn: ${EXTRA_ARGS_FILE} has an unknown format-version; ignoring it (re-run 'cmake --preset debug' to regenerate)." >&2
else
  while IFS= read -r line; do
    case "$line" in
      '#'*) ;;
      '') ;;
      --extra-arg=-isystem/*) EXTRA_ARGS+=("$line") ;;
      *) echo "warn: ignoring malformed line in ${EXTRA_ARGS_FILE}: ${line}" >&2 ;;
    esac
  done < "${EXTRA_ARGS_FILE}"
fi

# Resolve the same clang-tidy binary CMake found so diagnostics match the build.
CLANG_TIDY="$(cmake -LA -N "${BUILD_DIR}" 2>/dev/null \
  | awk -F= '/^CLANGTIDY:FILEPATH=/ {print $2; exit}')"
if [ -z "${CLANG_TIDY}" ]; then
  CLANG_TIDY="$(command -v clang-tidy || true)"
fi
if [ -z "${CLANG_TIDY}" ]; then
  echo "error: clang-tidy not found (CMake cache empty and not on PATH)" >&2
  exit 1
fi

# \( ... \) groups the -name predicates: without it -o binds loosely across the
# multiple root paths and find scans more (and wrong) files than intended.
find "${ROOT_DIR}/include" "${ROOT_DIR}/src" "${ROOT_DIR}/test" \
  \( -name "*.cpp" -o -name "*.hpp" \) -print |
  xargs "${CLANG_TIDY}" \
    -p "${BUILD_DIR}" \
    --config-file="${ROOT_DIR}/.clang-tidy" \
    "${EXTRA_ARGS[@]}" \
    "$@"
